version: '3.8'

services:
  mysqldb:
    container_name: mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - ./data/:/var/lib/mysql
    networks:
      - gs-network
  
  msconsulta:
    container_name: msconsulta
    image: msconsulta:v1
    restart: always
    ports:
      - 8080:8080
    networks:
      - gs-netowk

networks:
    gs-network:
        driver: bridge